### ISSUE TITLE
Support multiple repositories

### ISSUE THREAD

**Issue by beatngu13** [retest/rebazer#7]
`ReBaZerConfig` should be adapted such that multiple repositories can be defined. Therefore, we should also change how the external configuration takes place. For instance, [Spring Boot also supports YAML](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml):

```yaml
rebazer:
   user: service_user
   pass: dont_use_this_pass_at_home
   team: your_company
   workspace: ./rebazer-workspace
   repos:
       - foo
       - bar
       - baz
```
